<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "site_generator_customized"
 *
 * Auto generated by Extension Builder 2019-09-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Site generator customized',
    'description' => 'Add more steps and data to site generator extension',
    'category' => 'plugin',
    'author' => 'Florian Rival',
    'author_email' => 'florian.typo3@oktopuce.fr',
    'state' => 'stable',
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.5.99',
            'site_generator' => '2.0.0-2.9.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
